title: <p align="center"> Nathan Nougué </p>

logo: "/images/picture.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nathan-nougu%C3%A9-36b02382/">LinkedIn</a> |
  <a href="https://github.com/Nathannous">GitHub</a>
  </p>
  
  <p align="justify">
  I am Data Scientist at the Data Science Team at the French Customs. 
  <br><br>
  I apply Buisness rules, Deep and Machine Learing Algorithms for fraud detection with a focus on Graphs and Time Series.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
#google_analytics: # Google Analytics tracking ID
